### PR TITLE
Api endpoints validations

### PR DESCRIPTION
**Pull request by AdrianC113**

### CODE REVIEW

**Review by triciasykes — CHANGES_REQUESTED** [review]
Please remove all the commented out code from the registrations_controller

**Comment by AdrianC113** [comment]
Completed removal of commented out code from registration_controller. Thank you!

**Comment by AdrianC113** [comment]
Completed removal of commented out code from sessions_controller as well as other files. Thank you!

**Review by triciasykes — APPROVED** [review]
Well done!

**Pull request merged**
